export const FETCH_LINKSINBIO_START = 'FETCH_LINKSINBIO_START';
export const FETCH_LINKSINBIO_SUCCESS = 'FETCH_LINKSINBIO_SUCCESS';
export const FETCH_LINKSINBIO_FAIL = 'FETCH_LINKSINBIO_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN';
export const AUTH_LOGGED_OUT = 'AUTH_LOGGED_OUT';
export const AUTH_FAIL = 'AUTH_FAIL';

export const FETCH_TUTORIAL_START = 'FETCH_TUTORIAL_START'
export const FETCH_TUTORIAL_SUCCESS = 'FETCH_TUTORIAL_SUCCESS'
export const FETCH_TUTORIAL_FAIL = 'FETCH_TUTORIAL_FAIL'